# Generated by Django 5.2 on 2025-04-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=255, unique=True)),
                ("user_password", models.CharField(max_length=255)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("user", "普通用户"), ("admin", "管理员")], max_length=255
                    ),
                ),
            ],
            options={
                "db_table": "user_info",
            },
        ),
    ]
